// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { pathToFileURL } from "node:url";
import "dotenv/config";
import { defineConfig } from "prisma/config";

const defaultSqliteUrl = pathToFileURL(
  path.join(process.cwd(), "prisma", "dev.db"),
).href;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? defaultSqliteUrl,
  },
});
